baseURL = "https://tatianavelasco.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Tatiana Velasco"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Tatiana Velasco R."
author = "Tatiana Velasco"
description = "Ph.D. student, Economics and Education – Columbia University"
profilePicture = "images/me.jpg"
keywords = "economics, education, columbia, colombia"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:tv2225@tc.columbia.edu"

[[params.socialIcons]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/TatiVelasco/"
    [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/tativelasco/"

 [[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/tatianavelascoro/"



## Menu items

[menu]

#  [[menu.main]]
#  name = "Home"
#  identifier = "home"
#  weight = 100
#  url = "/"

  #[[menu.main]]
  #name = "Research"
  #weight = 200
  #identifier = "research"
  #url = "research/"

  #[[menu.main]]
  #name = "CV"
  #weight = 300
  #identifier = "cv"
  #url = "cv/"

#  [[menu.main]]
#  name = "About"
#  weight = 400
#  identifier = "about"
#  url = "about/"

  #############################
  #############################
