baseurl = "http://www.tativvelasco.com"
title = "Tatiana Velasco"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Tatiana Velasco Rodriguez"
    description = "Tatiana's personal website"
    keywords = "economics, education, columbia, colombia"
    info = "Ph.D. student - Columbia University"
    avatarurl = "images/me.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/tativelasco/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/TatiVelasco/"
#[[params.social]]
#    name = "LinkedIn"
#    icon = "fab fa-linkedin"
#    weight = 3
#    url = "https://www.linkedin.com/in/johndoe/"
#[[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 4
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "CV"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Research"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 4
            url = "contact/"


    [languages.pt-br]
        languagename = "Español"
        title = "Tatiana Velasco"

        [languages.pt-br.params]
            author = "Tatiana Velasco Rodriguez"
            info = "Estudiante Doctoral - Universidad de Columbia"
            description = "Website de Tatiana Velasco"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = ""

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Proyectos"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contacto"
            weight = 5
            url = "contact/"
